[package]
name = "init"
version = "0.2.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
constants = { path = "../libs/constants" }
libc = "0.2.*"
nix = "0.24"
