[package]
name = "target"
version = "0.2.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
crate-type = ["dylib"]
name = "target"

[dependencies]
basic = { path = "../../libs/basic" }
macros = { path = "../../libs/macros" }
sysmaster = { path = "../../" }

nix = "0.24"
log = "0.4"
serde = "1.0.130"
once_cell = { version = "1.5.2" }
