[package]
name = "init"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
constants = { version = "0.1.0", path = "../../libs/constants" }
libc = "0.2.*"
nix = "0.24"
signal-hook-registry = "1.4.0"
